"""Rename comment_mode to commenting_policy

Revision ID: 1a42c2fd3a28
Revises: 7b20d18649a8
Create Date: 2025-06-22 13:03:16.190579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a42c2fd3a28'
down_revision: Union[str, Sequence[str], None] = '7b20d18649a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_table', 'comment_policy',
               existing_type=postgresql.ENUM('everyone', 'followers', 'mentioned', 'none', name='comment_model'),
               type_=sa.Enum('everyone', 'followers', name='commenting_policy'),
               existing_nullable=False,
               postgresql_using="comment_policy::text::commenting_policy"
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_table', 'comment_policy',
               existing_type=sa.Enum('everyone', 'followers', name='commenting_policy'),
               type_=postgresql.ENUM('everyone', 'followers', 'mentioned', 'none', name='comment_model'),
               existing_nullable=False)
    # ### end Alembic commands ###
