"""Rename scheduled_time to scheduled_at

Revision ID: 41e9270b697a
Revises: 5f272f954c8b
Create Date: 2025-06-23 16:28:55.036438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41e9270b697a'
down_revision: Union[str, Sequence[str], None] = '5f272f954c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_table', sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('feed_table', 'scheduled_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_table', sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('feed_table', 'scheduled_at')
    # ### end Alembic commands ###
