"""renamed to quote_id from quoted_feed_id

Revision ID: 8c9c417eb34f
Revises: b77bfad0202e
Create Date: 2025-06-24 19:03:28.195038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9c417eb34f'
down_revision: Union[str, Sequence[str], None] = 'b77bfad0202e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_table', sa.Column('quote_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('feed_table_quoted_feed_id_fkey'), 'feed_table', type_='foreignkey')
    op.create_foreign_key(None, 'feed_table', 'feed_table', ['quote_id'], ['id'])
    op.drop_column('feed_table', 'quoted_feed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_table', sa.Column('quoted_feed_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feed_table', type_='foreignkey')
    op.create_foreign_key(op.f('feed_table_quoted_feed_id_fkey'), 'feed_table', 'feed_table', ['quoted_feed_id'], ['id'])
    op.drop_column('feed_table', 'quote_id')
    # ### end Alembic commands ###
