"""Rename scheduled_time to scheduled_at again

Revision ID: b77bfad0202e
Revises: 41e9270b697a
Create Date: 2025-06-23 17:02:01.134928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b77bfad0202e'
down_revision: Union[str, Sequence[str], None] = '41e9270b697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message_table', sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('chat_message_table', 'scheduled_time')
    op.drop_column('feed_table', 'display_dislikes')
    op.add_column('group_message_table', sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('group_message_table', 'scheduled_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_message_table', sa.Column('scheduled_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('group_message_table', 'scheduled_at')
    op.add_column('feed_table', sa.Column('display_dislikes', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_message_table', sa.Column('scheduled_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('chat_message_table', 'scheduled_at')
    # ### end Alembic commands ###
