"""Rename commenting_policy to comment_policy back

Revision ID: b902c9568448
Revises: 1a42c2fd3a28
Create Date: 2025-06-22 16:04:44.588080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b902c9568448'
down_revision: Union[str, Sequence[str], None] = '1a42c2fd3a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_table', 'comment_policy',
               existing_type=postgresql.ENUM('everyone', 'followers', name='commenting_policy'),
               type_=sa.Enum('everyone', 'followers', name='comment_policy'),
               existing_nullable=False,
               postgresql_using="comment_policy::text::comment_policy"
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_table', 'comment_policy',
               existing_type=sa.Enum('everyone', 'followers', name='comment_policy'),
               type_=postgresql.ENUM('everyone', 'followers', name='commenting_policy'),
               existing_nullable=False)
    # ### end Alembic commands ###
