services:
  docker_api_agent:
    image: alpine/socat:latest
    ports:
      - "2376:2376"
    entrypoint: socat tcp-listen:2375,fork,reuseaddr,unix-connect:/var/run/docker.sock
    networks:
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  traefik-network:
    external: true
    driver: overlay
