global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi"
    dns_sd_configs:
      - names:
          - "tasks.fastapi_fastapi"
        type: "A"
        port: 8000

  - job_name: "cadvisor"
    dns_sd_configs:
      - names:
          - "tasks.cadvisor_cadvisor"
        type: "A"
        port: 8080

  - job_name: "node_exporter"
    dns_sd_configs:
      - names:
          - "tasks.node_exporter_node_exporter"
        type: "A"
        port: 9100
